services:
    Sandronimus\NelmioFormGetParameterPluginBundle\Services\FormGetParameterRouteDescriber:
        autowire: true
        autoconfigure: true
        tags:
            - 'nelmio_api_doc.route_describer'
